### ISSUE TITLE
好朋友們的網站——布丁的連結已不再可用

### ISSUE THREAD

**Issue by fanlan1210** [fanlan1210/fanlan1210.github.io#1]
如題，在[網站首頁的「聯絡與更多」](https://www.fanlan.net/#contact)裡面，布丁的網站連結( https://web.cc.ncu.edu.tw/~109502533 )已經無法存取，需要移除或進行更新。

![image](https://github.com/fanlan1210/fanlan1210.github.io/assets/22187384/d7dc0176-bcb6-485d-932e-d78a8adf349f)

**Comment by fanlan1210** [comment]
@pudding0803 想詢問看看你的想法~

**Comment by pudding0803** [comment]
> @pudding0803 想詢問看看你的想法~

噢不我畢業結果網站被學校刪了🥲🥲，看來是時候用 [GitHub Pages](pudding0803.github.io) 了(?)，但我架好先暫時放著，之後再把內容修好🫠🫠

**Comment by fanlan1210** [comment]
> > @pudding0803 想詢問看看你的想法~
> 
> 噢不我畢業結果網站被學校刪了🥲🥲，看來是時候用 [GitHub Pages](pudding0803.github.io) 了(?)，但我架好先暫時放著，之後再把內容修好🫠🫠

好的，我之後更新成 GitHub 的這個網址！
