### ISSUE TITLE
好朋友們的網站——念誠的連結已不再可用

### ISSUE THREAD

**Issue by fanlan1210** [fanlan1210/fanlan1210.github.io#2]
如題，在[網站首頁的「聯絡與更多」](https://www.fanlan.net/#contact)裡面，念誠的網站連結( https://ncchen.ga/ )已經無法存取，需要移除或進行更新。

![image](https://github.com/fanlan1210/fanlan1210.github.io/assets/22187384/987126d4-cf81-44d6-9e96-b276e12a02cb)

**Comment by fanlan1210** [comment]
@ncchen99 請求支援QwQ

**Comment by ncchen99** [comment]
.ga 壞光光ㄌ😆 現在直接用 GitHub 的！

ncchen99.github.io

謝謝智仁🥰

**Comment by fanlan1210** [comment]
> ga 壞光光ㄌ😆 現在直接用 GitHub 的！
>
> [ncchen99.github.io](http://ncchen99.github.io/)

好的，我會更新上去owo
